export enum GLOBAL_ACTION_TYPES {
  SET_OPEN_START = "SET_OPEN_START",
  SET_OPEN_SUCCESS = "SET_OPEN_SUCCESS",
  SET_OPEN_FAILED = "SET_OPEN_FAILED",

  SET_TOKEN_START = "SET_TOKEN_START",
  SET_TOKEN_SUCCESS = "SET_TOKEN_SUCCESS",
  SET_TOKEN_FAILED = "SET_TOKEN_FAILED",
}
